// Type definitions
export interface SudetenRange {
  id: number;
  rank: number;
  name: string;
  nameCs: string;
  nameDe: string;
  peak: string;
  peakCs: string;
  peakDe?: string;
  elevation: number;
  country: string;
  isKs: boolean; // Korona Sudetów
  isKgp: boolean; // Korona Gór Polski
  imageUrl?: string; // URL zdjęcia szczytu
}

export interface KgpPeak {
  id: number;
  name: string;
  code: string;
  elevation: number;
  range: string;
}

// Dane wszystkich szczytów uporządkowane od najwyższego do najniższego
export const sudetenRanges: SudetenRange[] = [
  {
    id: 1,
    rank: 1,
    name: 'Karkonosze',
    nameCs: 'Krkonoše',
    nameDe: 'Riesengebirge',
    peak: 'Śnieżka',
    peakCs: 'Sněžka',
    peakDe: 'Schneekoppe',
    elevation: 1603,
    country: 'PL/CZ',
    isKs: true,
    isKgp: true,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_gY_T/f3RVVv.jpeg?fl=res,,500,1',
  },
  {
    id: 2,
    rank: 2,
    name: 'Wysoki Jesionik',
    nameCs: 'Hrubý Jeseník',
    nameDe: 'Altvatergebirge',
    peak: 'Pradziad',
    peakCs: 'Praděd',
    peakDe: 'Altvater',
    elevation: 1491,
    country: 'CZ',
    isKs: true,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_gW_p/HIydYU.jpeg?fl=res,,500,1',
  },
  {
    id: 3,
    rank: 3,
    name: 'Masyw Śnieżnika',
    nameCs: 'Králický Sněžník',
    nameDe: 'Glatzer Schneegebirge',
    peak: 'Śnieżnik',
    peakCs: 'Králický Sněžník',
    peakDe: 'Glatzer Schneegebirge',
    elevation: 1426,
    country: 'PL/CZ',
    isKs: true,
    isKgp: true,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_QQ_f/21iGzM.jpeg?fl=res,,500,1',
  },
  {
    id: 4,
    rank: 4,
    name: 'Karkonosze',
    nameCs: 'Krkonoše',
    nameDe: 'Riesengebirge',
    peak: 'Skalny Stół',
    peakCs: 'Skalní stůl',
    peakDe: 'Steinerner Tisch',
    elevation: 1284,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_gY_5/HhqXgh.jpeg?fl=rot,180,0%7Cres,,500,1',
  },
  {
    id: 5,
    rank: 5,
    name: 'Karkonosze',
    nameCs: 'Krkonoše',
    nameDe: 'Riesengebirge',
    peak: 'Łysocina',
    peakCs: 'Lysečinská hora',
    peakDe: 'Geiergucke',
    elevation: 1188,
    country: 'PL/CZ',
    isKs: false,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_G_W/hyN3UJ.jpeg?fl=res,,500,1',
  },
  {
    id: 6,
    rank: 6,
    name: 'Góry Złote',
    nameCs: 'Rychlebské hory',
    nameDe: 'Reichensteiner Gebirge',
    peak: 'Smrek',
    peakCs: 'Smrk',
    peakDe: 'Reichenstein',
    elevation: 1127,
    country: 'PL/CZ',
    isKs: true,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_QN_2/lUpg9J.jpeg?fl=res,,500,1',
  },
  {
    id: 7,
    rank: 7,
    name: 'Góry Izerskie',
    nameCs: 'Jizerské hory',
    nameDe: 'Isergebirge',
    peak: 'Wysoka Kopa',
    peakCs: 'Vysoká Kopa',
    peakDe: 'Hohes Isergebirge',
    elevation: 1126,
    country: 'PL/CZ',
    isKs: true,
    isKgp: true,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_H_T/gR8BeBW.jpeg?fl=res,,500,1',
  },
  {
    id: 8,
    rank: 8,
    name: 'Góry Izerskie',
    nameCs: 'Jizerské hory',
    nameDe: 'Isergebirge',
    peak: 'Smrk',
    peakCs: 'Smrk',
    peakDe: 'Tafelfichte',
    elevation: 1124,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_QR_5/IXDEH5.jpeg?fl=res,,500,1',
  },
  {
    id: 9,
    rank: 9,
    name: 'Góry Orlickie',
    nameCs: 'Orlické hory',
    nameDe: 'Adlergebirge',
    peak: 'Velká Deštná',
    peakCs: 'Velká Deštná',
    peakDe: 'Adlergebirge',
    elevation: 1115,
    country: 'CZ',
    isKs: true,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_gZ_R/ePxDlu.jpeg?fl=res,,500,1',
  },
  {
    id: 10,
    rank: 10,
    name: 'Góry Bialskie',
    nameCs: 'Bělské hory',
    nameDe: 'Bielengebirge',
    peak: 'Rudawiec',
    peakCs: 'Rudaviec',
    peakDe: 'Riedelberg',
    elevation: 1112,
    country: 'PL/CZ',
    isKs: false,
    isKgp: true,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_QP_l/90RIpm.mpo?fl=res,,500,1',
  },
  {
    id: 11,
    rank: 11,
    name: 'Góry Orlickie',
    nameCs: 'Orlické hory',
    nameDe: 'Adlergebirge',
    peak: 'Orlica',
    peakCs: 'Orlice',
    peakDe: 'Adlergebirge',
    elevation: 1084,
    country: 'PL',
    isKs: false,
    isKgp: true,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_gS_q/HC8l6H.jpeg?fl=res,,500,1',
  },
  {
    id: 12,
    rank: 12,
    name: 'Góry Izerskie',
    nameCs: 'Jizerské hory',
    nameDe: 'Isergebirge',
    peak: 'Wysoki Kamień',
    peakCs: 'Wysoký kámen',
    peakDe: 'Hoher Stein',
    elevation: 1058,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_gR_o/XW0Fwq.jpeg?fl=res,2200,2200,1',
  },
  {
    id: 13,
    rank: 13,
    name: 'Góry Sowie',
    nameCs: 'Soví hory',
    nameDe: 'Eulengebirge',
    peak: 'Wielka Sowa',
    peakCs: 'Soví hora',
    peakDe: 'Eulenkoppe',
    elevation: 1015,
    country: 'PL/CZ',
    isKs: true,
    isKgp: true,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_QJ_v/xPoV6s.jpeg?fl=res,,500,1',
  },
  {
    id: 14,
    rank: 14,
    name: 'Grzbiet Jesztedzko-Kozakowski',
    nameCs: 'Ještědsko-kozákovský hřbet',
    nameDe: 'Jeschken-Kosakow-Kamm',
    peak: 'Ještěd',
    peakCs: 'Ještěd',
    peakDe: 'Jeschken',
    elevation: 1012,
    country: 'CZ',
    isKs: true,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_gW_f/WNtH0o.jpeg?fl=res,,500,1',
  },
  {
    id: 15,
    rank: 15,
    name: 'Hanušovická vrchovina',
    nameCs: 'Hanušovická vrchovina',
    nameDe: 'Hannsdorfer Bergland',
    peak: 'Jeřáb',
    peakCs: 'Jeřáb',
    peakDe: 'Hannsdorfer Bergland',
    elevation: 1003,
    country: 'CZ',
    isKs: true,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_QO_N/2qKNS.jpeg?fl=res,,500,1',
  },
  {
    id: 16,
    rank: 16,
    name: 'Góry Złote',
    nameCs: 'Rychlebské hory',
    nameDe: 'Reichensteiner Gebirge',
    peak: 'Kowadło',
    peakCs: 'Kladský vrch',
    peakDe: 'Reichenstein',
    elevation: 989,
    country: 'PL',
    isKs: false,
    isKgp: true,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_gX_e/Dmj5ru.jpeg?fl=res,,500,1',
  },
  {
    id: 17,
    rank: 17,
    name: 'Góry Bystrzyckie',
    nameCs: 'Bystřické hory',
    nameDe: 'Habelschwerdter Gebirge',
    peak: 'Jagodna Północna',
    peakCs: 'Jagodná',
    peakDe: 'Habelschwerdter Gebirge',
    elevation: 985,
    country: 'PL',
    isKs: true,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_oZ_A/kBkJRwehYQKXlCDPDMpU7r/c11b.jpeg?fl=res,,500,1',
  },
  {
    id: 18,
    rank: 18,
    name: 'Góry Bystrzyckie',
    nameCs: 'Bystřické hory',
    nameDe: 'Habelschwerdter Gebirge',
    peak: 'Jagodna',
    peakCs: 'Jagodná',
    peakDe: 'Habelschwerdter Gebirge',
    elevation: 977,
    country: 'PL',
    isKs: false,
    isKgp: true,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_QM_y/h4Un27.jpeg?fl=res,,500,1',
  },
  {
    id: 19,
    rank: 19,
    name: 'Góry Opawskie',
    nameCs: 'Zlatohorská vrchovina',
    nameDe: 'Zuckmanteler Bergland',
    peak: 'Góra Poprzeczna',
    peakCs: 'Příčný vrch',
    peakDe: 'Zuckmanteler Bergland',
    elevation: 975,
    country: 'PL/CZ',
    isKs: true,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_gU_h/ACbNtQ.mpo?fl=res,,500,1',
  },
  {
    id: 20,
    rank: 20,
    name: 'Karkonosze',
    nameCs: 'Krkonoše',
    nameDe: 'Riesengebirge',
    peak: 'Hvězda',
    peakCs: 'Hvězda',
    peakDe: 'Die Sterne',
    elevation: 959,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_QP_BJ/llLHyl.mpo?fl=res,,500,1',
  },
  {
    id: 21,
    rank: 21,
    name: 'Rudawy Janowickie',
    nameCs: 'Janovické rudohoří',
    nameDe: 'Landeshuter Kamm',
    peak: 'Ostra Mała',
    peakCs: 'Ostrá malá',
    peakDe: 'Spitzkoppe',
    elevation: 945,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_QM_W/OMquq.jpeg?fl=res,,500,1',
  },
  {
    id: 22,
    rank: 22,
    name: 'Rudawy Janowickie',
    nameCs: 'Janovické rudohoří',
    nameDe: 'Landeshuter Kamm',
    peak: 'Skalnik',
    peakCs: 'Skalník',
    peakDe: 'Skalnik',
    elevation: 945,
    country: 'PL/CZ',
    isKs: true,
    isKgp: true,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_ob_B/kBj94XhVwDuD8OBlID4Xp4i/7bbd.jpeg?fl=res,,500,1',
  },
  {
    id: 23,
    rank: 23,
    name: 'Góry Kamienne',
    nameCs: 'Vraní hory / Javoří hory',
    nameDe: 'Steingebirge',
    peak: 'Waligóra',
    peakCs: 'Vraní hory / Javoří hory',
    peakDe: 'Steingebirge',
    elevation: 936,
    country: 'PL',
    isKs: true,
    isKgp: true,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_QN_o/NSOFpE.mpo?fl=res,,500,1',
  },
  {
    id: 24,
    rank: 24,
    name: 'Góry Opawskie',
    nameCs: 'Zlatohorská vrchovina',
    nameDe: 'Zuckmanteler Bergland',
    peak: 'Zámecký vrch',
    peakCs: 'Zámecký vrch',
    peakDe: 'Schlossberg',
    elevation: 934,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_QO_8/LavBKN.jpeg?fl=res,,500,1',
  },
  {
    id: 25,
    rank: 25,
    name: 'Góry Stołowe',
    nameCs: 'Stolové hory',
    nameDe: 'Heuscheuergebirge',
    peak: 'Szczeliniec Wielki',
    peakCs: 'Stolová hora',
    peakDe: 'Heuscheuer',
    elevation: 919,
    country: 'PL/CZ',
    isKs: true,
    isKgp: true,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_QP_BG/M0u4F9.jpeg?fl=res,,500,1',
  },
  {
    id: 26,
    rank: 26,
    name: 'Góry Bialskie',
    nameCs: 'Bělské hory',
    nameDe: 'Bielengebirge',
    peak: 'Větrov',
    peakCs: 'Větrov',
    peakDe: '',
    elevation: 918,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_QO_6/9hkB6P6.mpo?fl=res,,500,1',
  },
  {
    id: 27,
    rank: 27,
    name: 'Góry Opawskie',
    nameCs: 'Zlatohorská vrchovina',
    nameDe: 'Zuckmanteler Bergland',
    peak: 'Biskupia Kopa',
    peakCs: 'Biskupská kupa',
    peakDe: 'Zuckmanteler Bergland',
    elevation: 890,
    country: 'PL',
    isKs: false,
    isKgp: true,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_gR_n/K91F2O.jpeg?fl=res,,500,1',
  },
  {
    id: 28,
    rank: 28,
    name: 'Rudawy Janowickie',
    nameCs: 'Janovické rudohoří',
    nameDe: 'Landeshuter Kamm',
    peak: 'Wołek',
    peakCs: 'Volek',
    peakDe: 'Ochsberg',
    elevation: 878,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_oc_A/kcukOQcMmRUmqByJEBUujI/ac3f.jpeg?fl=res,,500,1',
  },
  {
    id: 29,
    rank: 29,
    name: 'Góry Wałbrzyskie',
    nameCs: 'Valbřišské hory',
    nameDe: 'Waldenburgergebirge',
    peak: 'Borowa',
    peakCs: 'Borowa',
    peakDe: 'Borowa',
    elevation: 853,
    country: 'PL',
    isKs: true,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_QL_1/zWfBYIM.jpeg?fl=res,,500,1',
  },
  {
    id: 30,
    rank: 30,
    name: 'Góry Wałbrzyskie',
    nameCs: 'Valbřišské hory',
    nameDe: 'Waldenburgergebirge',
    peak: 'Chełmiec',
    peakCs: 'Chelmec',
    peakDe: 'Chelmzberg',
    elevation: 851,
    country: 'PL',
    isKs: false,
    isKgp: true,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_E_L/ucSIp.jpeg?fl=res,,500,1',
  },
  {
    id: 31,
    rank: 31,
    name: 'Masyw Śnieżnika',
    nameCs: 'Králický Sněžník',
    nameDe: 'Glatzer Schneegebirge',
    peak: 'Igliczna',
    peakCs: 'Iglišná',
    peakDe: 'Igelberg',
    elevation: 845,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_oe_A/kOzmiQlmfoQAuL6JEmRKoN/10fc.jpeg?fl=res,,500,1',
  },
  {
    id: 32,
    rank: 32,
    name: 'Góry Sowie',
    nameCs: 'Soví hory',
    nameDe: 'Eulengebirge',
    peak: 'Włodarz',
    peakCs: 'Vladař',
    peakDe: 'Waldenburger Berg',
    elevation: 811,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_gZ_8/MJrgkC.jpeg?fl=res,,500,1',
  },
  {
    id: 33,
    rank: 33,
    name: 'Góry Wałbrzyskie',
    nameCs: 'Valbřišské hory',
    nameDe: 'Waldenburgergebirge',
    peak: 'Gomólnik Mały',
    peakCs: 'Gomolník',
    peakDe: 'Kleiner Kammelberg',
    elevation: 807,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_gR_z/ZWoNj6.jpeg?fl=res,,500,1',
  },
  {
    id: 34,
    rank: 34,
    name: 'Niski Jesionik',
    nameCs: 'Nízký Jeseník',
    nameDe: 'Niederes Gesenke',
    peak: 'Slunečná',
    peakCs: 'Slunečná',
    peakDe: 'Niederes Gesenke',
    elevation: 800,
    country: 'CZ',
    isKs: true,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_QI_w/IL8BG40.jpeg?fl=res,,500,1',
  },
  {
    id: 35,
    rank: 35,
    name: 'Góry Łużyckie',
    nameCs: 'Lužické hory',
    nameDe: 'Lausitzer Gebirge',
    peak: 'Luž / Lausche',
    peakCs: 'Luž',
    peakDe: 'Lausche',
    elevation: 793,
    country: 'PL/CZ',
    isKs: true,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_gS_o/lHvqYn.jpeg?fl=res,,500,1',
  },
  {
    id: 36,
    rank: 36,
    name: 'Grzbiet Jesztedzko-Kozakowski',
    nameCs: 'Ještědsko-kozákovský hřbet',
    nameDe: 'Jeschken-Kosakow-Kamm',
    peak: 'Vápenný',
    peakCs: 'Vápenný',
    peakDe: 'Kalkberg',
    elevation: 790,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_E_L/t1QBOd.jpeg?fl=res,,500,1',
  },
  {
    id: 37,
    rank: 37,
    name: 'Góry Izerskie',
    nameCs: 'Jizerské hory',
    nameDe: 'Isergebirge',
    peak: 'Muchov',
    peakCs: 'Muchov',
    peakDe: 'Muxberg',
    elevation: 787,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_QR_2/pSVGiD.mpo?fl=res,,500,1',
  },
  {
    id: 38,
    rank: 38,
    name: 'Góry Wałbrzyskie',
    nameCs: 'Valbřišské hory',
    nameDe: 'Waldenburgergebirge',
    peak: 'Wołowiec',
    peakCs: 'Volovec',
    peakDe: 'Ochsberg',
    elevation: 776,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_oa_A/nO7kYQIzllDshrEBXuDiT20x/fc81.jpeg?fl=res,,500,1',
  },
  {
    id: 39,
    rank: 39,
    name: 'Góry Bardzkie',
    nameCs: 'Bardské hory',
    nameDe: 'Warthagebirge',
    peak: 'Szeroka Góra',
    peakCs: 'Bardská hora',
    peakDe: 'Warthagebirge',
    elevation: 765,
    country: 'PL',
    isKs: true,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_gX_o/EWrGt3.jpeg?fl=res,,500,1',
  },
  {
    id: 40,
    rank: 40,
    name: 'Góry Bardzkie',
    nameCs: 'Bardské hory',
    nameDe: 'Warthagebirge',
    peak: 'Kłodzka Góra',
    peakCs: 'Kladská hora',
    peakDe: 'Warthagebirge',
    elevation: 757,
    country: 'PL',
    isKs: false,
    isKgp: true,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_QJ_w/41nfE6.jpeg?fl=res,,500,1',
  },
  {
    id: 41,
    rank: 41,
    name: 'Góry Jastrzębie',
    nameCs: 'Žacléřská vrchovina',
    nameDe: 'Habichtgebirge',
    peak: 'Žaltman',
    peakCs: 'Žaltman',
    peakDe: 'Habicht',
    elevation: 739,
    country: 'CZ',
    isKs: true,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_gU_5/jfNE4x.jpeg?fl=res,,500,1',
  },
  {
    id: 42,
    rank: 42,
    name: 'Góry Kaczawskie',
    nameCs: 'Kačavské hory',
    nameDe: 'Bober-Katzbach-Gebirge',
    peak: 'Skopiec',
    peakCs: 'Skopiec',
    peakDe: 'Skopetz',
    elevation: 724,
    country: 'PL',
    isKs: true,
    isKgp: true,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_oY_A/nsLxLojIIE33fGC4jmXp/1429.jpeg?fl=res,,500,1',
  },
  {
    id: 43,
    rank: 43,
    name: 'Góry Izerskie',
    nameCs: 'Jizerské hory',
    nameDe: 'Isergebirge',
    peak: 'Špičák',
    peakCs: 'Špičák',
    peakDe: 'Spitzberg',
    elevation: 724,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_oZ_A/kBkJRwehYBM7PH96DSXdt0/60ab.jpeg?fl=res,,500,1',
  },
  {
    id: 44,
    rank: 44,
    name: 'Góry Kaczawskie',
    nameCs: 'Kačavské hory',
    nameDe: 'Bober-Katzbach-Gebirge',
    peak: 'Baraniec',
    peakCs: 'Baraniec',
    peakDe: 'Widderberg',
    elevation: 720,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_oW_A/kPWmeC9soBDmlC1UjCcedyp/7a93.jpeg?fl=res,,500,1',
  },
  {
    id: 45,
    rank: 45,
    name: 'Góry Kaczawskie',
    nameCs: 'Kačavské hory',
    nameDe: 'Bober-Katzbach-Gebirge',
    peak: 'Okole',
    peakCs: 'Okole',
    peakDe: 'Ockelberg',
    elevation: 718,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_gU_i/Lk2ENs.jpeg?fl=res,,500,1',
  },
  {
    id: 46,
    rank: 46,
    name: 'Masyw Ślęży',
    nameCs: 'Slepá hora',
    nameDe: 'Zobtengebirge',
    peak: 'Ślęża',
    peakCs: 'Slepá hora',
    peakDe: 'Zobten',
    elevation: 718,
    country: 'PL',
    isKs: true,
    isKgp: true,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_gW_e/r3koNk.mpo?fl=res,,500,1',
  },
  {
    id: 47,
    rank: 47,
    name: 'Zábřežská vrchovina',
    nameCs: 'Zábřežská vrchovina',
    nameDe: 'Hohenstädter Bergland',
    peak: 'Lázek',
    peakCs: 'Lázek',
    peakDe: 'Hohenstädter Bergland',
    elevation: 714,
    country: 'CZ',
    isKs: true,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_E_M/9EMY0F.jpeg?fl=res,,500,1',
  },
  {
    id: 48,
    rank: 48,
    name: 'Góry Kamienne',
    nameCs: 'Vraní hory / Javoří hory',
    nameDe: 'Steingebirge',
    peak: 'Boreczna',
    peakCs: 'Borečná',
    peakDe: 'Borschener Berg',
    elevation: 710,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_ob_A/nPTQKDwGerDgEH8a9Dta14D/6940.jpeg?fl=res,,500,1',
  },
  {
    id: 49,
    rank: 49,
    name: 'Niski Jesionik',
    nameCs: 'Nízký Jeseník',
    nameDe: 'Niederes Gesenke',
    peak: 'Pomezí',
    peakCs: 'Pomezí',
    peakDe: '',
    elevation: 707,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_QN_y/pm1F8V.jpeg?fl=res,,500,1',
  },
  {
    id: 50,
    rank: 50,
    name: 'Góry Bystrzyckie',
    nameCs: 'Bystřické hory',
    nameDe: 'Habelschwerdter Gebirge',
    peak: 'Kamienna Góra',
    peakCs: 'Kamienna Góra',
    peakDe: 'Steinberg',
    elevation: 704,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_QM_l/ucHMKh.jpeg?fl=res,,500,1',
  },
  {
    id: 51,
    rank: 51,
    name: 'Góry Jastrzębie',
    nameCs: 'Žacléřská vrchovina',
    nameDe: 'Habichtgebirge',
    peak: 'Jański Wierch',
    peakCs: 'Janský vrch',
    peakDe: 'Johannisberg',
    elevation: 697,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_gT_r/8sMBza.jpeg?fl=res,,500,1',
  },
  {
    id: 52,
    rank: 52,
    name: 'Grzbiet Jesztedzko-Kozakowski',
    nameCs: 'Ještědsko-kozákovský hřbet',
    nameDe: 'Jeschken-Kosakow-Kamm',
    peak: 'Javorník',
    peakCs: 'Javorník',
    peakDe: 'Jauerling',
    elevation: 684,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/d_15120355/img/8/960x720_5OfVZo.jpg?fl=res,,500,1',
  },
  {
    id: 53,
    rank: 53,
    name: 'Góry Wałbrzyskie',
    nameCs: 'Valbřišské hory',
    nameDe: 'Waldenburgergebirge',
    peak: 'Niedźwiadki',
    peakCs: 'Medvídky',
    peakDe: 'Bärenberg',
    elevation: 629,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_H_I/q0JBO6e.jpeg?fl=res,,500,1',
  },
  {
    id: 54,
    rank: 54,
    name: 'Masyw Śnieżnika',
    nameCs: 'Králický Sněžník',
    nameDe: 'Glatzer Schneegebirge',
    peak: 'Wapniarka',
    peakCs: 'Wapniarka',
    peakDe: 'Kalkberg',
    elevation: 532,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_ob_A/kBj94XhVwBhVo6BRFDw05Ml/d53d.mpo?fl=res,,500,1',
  },
  {
    id: 55,
    rank: 55,
    name: 'Góry Stołowe',
    nameCs: 'Stolové hory',
    nameDe: 'Heuscheuergebirge',
    peak: 'Guzowata',
    peakCs: 'Guzowata',
    peakDe: 'Gusseberg',
    elevation: 492,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: 'https://d34-a.sdn.cz/d_34/c_img_gV_Z/NY4DV3.jpeg?fl=res,,500,1',
  },
];

// Korona Gór Polski - Sudety (16 szczytów)
export const koronaGorPolski: KgpPeak[] = [
  {
    id: 1,
    name: 'Śnieżka',
    code: 'KGP 03',
    elevation: 1603,
    range: 'Karkonosze',
  },
  {
    id: 2,
    name: 'Śnieżnik',
    code: 'KGP 04',
    elevation: 1425,
    range: 'Masyw Śnieżnika',
  },
  {
    id: 3,
    name: 'Wysoka Kopa',
    code: 'KGP 10',
    elevation: 1126,
    range: 'Góry Izerskie',
  },
  {
    id: 4,
    name: 'Rudawiec',
    code: 'KGP 11',
    elevation: 1115,
    range: 'Góry Bialskie',
  },
  {
    id: 5,
    name: 'Orlica',
    code: 'KGP 12',
    elevation: 1084,
    range: 'Góry Orlickie',
  },
  {
    id: 6,
    name: 'Wielka Sowa',
    code: 'KGP 14',
    elevation: 1015,
    range: 'Góry Sowie',
  },
  {
    id: 7,
    name: 'Kowadło',
    code: 'KGP 16',
    elevation: 989,
    range: 'Góry Złote',
  },
  {
    id: 8,
    name: 'Jagodna',
    code: 'KGP 17',
    elevation: 977,
    range: 'Góry Bystrzyckie',
  },
  {
    id: 9,
    name: 'Skalnik',
    code: 'KGP 18',
    elevation: 945,
    range: 'Rudawy Janowickie',
  },
  {
    id: 10,
    name: 'Waligóra',
    code: 'KGP 19',
    elevation: 936,
    range: 'Góry Kamienne',
  },
  {
    id: 11,
    name: 'Szczeliniec Wielki',
    code: 'KGP 21',
    elevation: 919,
    range: 'Góry Stołowe',
  },
  {
    id: 12,
    name: 'Biskupia Kopa',
    code: 'KGP 23',
    elevation: 890,
    range: 'Opawskie',
  },
  {
    id: 13,
    name: 'Chełmiec',
    code: 'KGP 24',
    elevation: 851,
    range: 'Góry Wałbrzyskie',
  },
  {
    id: 14,
    name: 'Kłodzka Góra',
    code: 'KGP 25',
    elevation: 765,
    range: 'Góry Bardzkie',
  },
  {
    id: 15,
    name: 'Skopiec',
    code: 'KGP 26',
    elevation: 724,
    range: 'Góry Kaczawskie',
  },
  {
    id: 16,
    name: 'Ślęża',
    code: 'KGP 27',
    elevation: 718,
    range: 'Masyw Ślęży',
  },
];

