export interface SudetenRange {
  id: number;
  rank: number;
  name: string;
  nameCs: string;
  nameDe: string;
  peak: string;
  peakCs: string;
  peakDe?: string;
  elevation: number;
  country: string;
  isKs: boolean; // Korona Sudetów
  isKgp: boolean; // Korona Gór Polski
  imageUrl?: string; // URL zdjęcia szczytu
}

// Dane wszystkich szczytów uporządkowane od najwyższego do najniższego
export const sudetenRanges: SudetenRange[] = [
  {
    id: 1,
    rank: 1,
    name: 'Karkonosze',
    nameCs: 'Krkonoše',
    nameDe: 'Riesengebirge',
    peak: 'Śnieżka',
    peakCs: 'Sněžka',
    peakDe: 'Schneekoppe',
    elevation: 1603,
    country: 'PL/CZ',
    isKs: true,
    isKgp: true,
    imageUrl: '/images/mountains/f3RVVv.jpeg',
  },
  {
    id: 2,
    rank: 2,
    name: 'Wysoki Jesionik',
    nameCs: 'Hrubý Jeseník',
    nameDe: 'Altvatergebirge',
    peak: 'Pradziad',
    peakCs: 'Praděd',
    peakDe: 'Altvater',
    elevation: 1491,
    country: 'CZ',
    isKs: true,
    isKgp: false,
    imageUrl: '/images/mountains/HIydYU.jpeg',
  },
  {
    id: 3,
    rank: 3,
    name: 'Masyw Śnieżnika',
    nameCs: 'Králický Sněžník',
    nameDe: 'Glatzer Schneegebirge',
    peak: 'Śnieżnik',
    peakCs: 'Králický Sněžník',
    peakDe: 'Glatzer Schneegebirge',
    elevation: 1426,
    country: 'PL/CZ',
    isKs: true,
    isKgp: true,
    imageUrl: '/images/mountains/21iGzM.jpeg',
  },
  {
    id: 4,
    rank: 4,
    name: 'Karkonosze',
    nameCs: 'Krkonoše',
    nameDe: 'Riesengebirge',
    peak: 'Skalny Stół',
    peakCs: 'Skalní stůl',
    peakDe: 'Steinerner Tisch',
    elevation: 1284,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl:
      '/images/mountains/HhqXgh.jpeg',
  },
  {
    id: 5,
    rank: 5,
    name: 'Karkonosze',
    nameCs: 'Krkonoše',
    nameDe: 'Riesengebirge',
    peak: 'Łysocina',
    peakCs: 'Lysečinská hora',
    peakDe: 'Geiergucke',
    elevation: 1188,
    country: 'PL/CZ',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/hyN3UJ.jpeg',
  },
  {
    id: 6,
    rank: 6,
    name: 'Góry Złote',
    nameCs: 'Rychlebské hory',
    nameDe: 'Reichensteiner Gebirge',
    peak: 'Smrek',
    peakCs: 'Smrk',
    peakDe: 'Reichenstein',
    elevation: 1127,
    country: 'PL/CZ',
    isKs: true,
    isKgp: false,
    imageUrl: '/images/mountains/lUpg9J.jpeg',
  },
  {
    id: 7,
    rank: 7,
    name: 'Góry Izerskie',
    nameCs: 'Jizerské hory',
    nameDe: 'Isergebirge',
    peak: 'Wysoka Kopa',
    peakCs: 'Vysoká Kopa',
    peakDe: 'Hohes Isergebirge',
    elevation: 1126,
    country: 'PL/CZ',
    isKs: true,
    isKgp: true,
    imageUrl: '/images/mountains/gR8BeBW.jpeg',
  },
  {
    id: 8,
    rank: 8,
    name: 'Góry Izerskie',
    nameCs: 'Jizerské hory',
    nameDe: 'Isergebirge',
    peak: 'Smrk',
    peakCs: 'Smrk',
    peakDe: 'Tafelfichte',
    elevation: 1124,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/IXDEH5.jpeg',
  },
  {
    id: 9,
    rank: 9,
    name: 'Góry Orlickie',
    nameCs: 'Orlické hory',
    nameDe: 'Adlergebirge',
    peak: 'Velká Deštná',
    peakCs: 'Velká Deštná',
    peakDe: 'Adlergebirge',
    elevation: 1115,
    country: 'CZ',
    isKs: true,
    isKgp: false,
    imageUrl: '/images/mountains/ePxDlu.jpeg',
  },
  {
    id: 10,
    rank: 10,
    name: 'Góry Bialskie',
    nameCs: 'Bělské hory',
    nameDe: 'Bielengebirge',
    peak: 'Rudawiec',
    peakCs: 'Rudaviec',
    peakDe: 'Riedelberg',
    elevation: 1112,
    country: 'PL/CZ',
    isKs: true,
    isKgp: true,
    imageUrl: '/images/mountains/90RIpm.jpeg',
  },
  {
    id: 11,
    rank: 11,
    name: 'Góry Orlickie',
    nameCs: 'Orlické hory',
    nameDe: 'Adlergebirge',
    peak: 'Orlica',
    peakCs: 'Orlice',
    peakDe: 'Adlergebirge',
    elevation: 1084,
    country: 'PL',
    isKs: false,
    isKgp: true,
    imageUrl: '/images/mountains/HC8l6H.jpeg',
  },
  {
    id: 12,
    rank: 12,
    name: 'Góry Izerskie',
    nameCs: 'Jizerské hory',
    nameDe: 'Isergebirge',
    peak: 'Wysoki Kamień',
    peakCs: 'Wysoký kámen',
    peakDe: 'Hoher Stein',
    elevation: 1058,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl:
      '/images/mountains/XW0Fwq.jpeg',
  },
  {
    id: 13,
    rank: 13,
    name: 'Góry Sowie',
    nameCs: 'Soví hory',
    nameDe: 'Eulengebirge',
    peak: 'Wielka Sowa',
    peakCs: 'Soví hora',
    peakDe: 'Eulenkoppe',
    elevation: 1015,
    country: 'PL/CZ',
    isKs: true,
    isKgp: true,
    imageUrl: '/images/mountains/xPoV6s.jpeg',
  },
  {
    id: 14,
    rank: 14,
    name: 'Grzbiet Jesztedzko-Kozakowski',
    nameCs: 'Ještědsko-kozákovský hřbet',
    nameDe: 'Jeschken-Kosakow-Kamm',
    peak: 'Ještěd',
    peakCs: 'Ještěd',
    peakDe: 'Jeschken',
    elevation: 1012,
    country: 'CZ',
    isKs: true,
    isKgp: false,
    imageUrl: '/images/mountains/WNtH0o.jpeg',
  },
  {
    id: 15,
    rank: 15,
    name: 'Hanušovická vrchovina',
    nameCs: 'Hanušovická vrchovina',
    nameDe: 'Hannsdorfer Bergland',
    peak: 'Jeřáb',
    peakCs: 'Jeřáb',
    peakDe: 'Hannsdorfer Bergland',
    elevation: 1003,
    country: 'CZ',
    isKs: true,
    isKgp: false,
    imageUrl: '/images/mountains/2qKNS.jpeg',
  },
  {
    id: 16,
    rank: 16,
    name: 'Góry Złote',
    nameCs: 'Rychlebské hory',
    nameDe: 'Reichensteiner Gebirge',
    peak: 'Kowadło',
    peakCs: 'Kladský vrch',
    peakDe: 'Reichenstein',
    elevation: 989,
    country: 'PL',
    isKs: false,
    isKgp: true,
    imageUrl: '/images/mountains/Dmj5ru.jpeg',
  },
  {
    id: 17,
    rank: 17,
    name: 'Góry Bystrzyckie',
    nameCs: 'Bystřické hory',
    nameDe: 'Habelschwerdter Gebirge',
    peak: 'Jagodna Północna',
    peakCs: 'Jagodná',
    peakDe: 'Habelschwerdter Gebirge',
    elevation: 985,
    country: 'PL',
    isKs: true,
    isKgp: false,
    imageUrl:
      '/images/mountains/c11b.jpeg',
  },
  {
    id: 18,
    rank: 18,
    name: 'Góry Bystrzyckie',
    nameCs: 'Bystřické hory',
    nameDe: 'Habelschwerdter Gebirge',
    peak: 'Jagodna',
    peakCs: 'Jagodná',
    peakDe: 'Habelschwerdter Gebirge',
    elevation: 977,
    country: 'PL',
    isKs: false,
    isKgp: true,
    imageUrl: '/images/mountains/h4Un27.jpeg',
  },
  {
    id: 19,
    rank: 19,
    name: 'Góry Opawskie',
    nameCs: 'Zlatohorská vrchovina',
    nameDe: 'Zuckmanteler Bergland',
    peak: 'Góra Poprzeczna',
    peakCs: 'Příčný vrch',
    peakDe: 'Zuckmanteler Bergland',
    elevation: 975,
    country: 'PL/CZ',
    isKs: true,
    isKgp: false,
    imageUrl: '/images/mountains/ACbNtQ.jpeg',
  },
  {
    id: 20,
    rank: 20,
    name: 'Karkonosze',
    nameCs: 'Krkonoše',
    nameDe: 'Riesengebirge',
    peak: 'Hvězda',
    peakCs: 'Hvězda',
    peakDe: 'Die Sterne',
    elevation: 959,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/llLHyl.jpeg',
  },
  {
    id: 21,
    rank: 21,
    name: 'Rudawy Janowickie',
    nameCs: 'Janovické rudohoří',
    nameDe: 'Landeshuter Kamm',
    peak: 'Ostra Mała',
    peakCs: 'Ostrá malá',
    peakDe: 'Spitzkoppe',
    elevation: 945,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/OMquq.jpeg',
  },
  {
    id: 22,
    rank: 22,
    name: 'Rudawy Janowickie',
    nameCs: 'Janovické rudohoří',
    nameDe: 'Landeshuter Kamm',
    peak: 'Skalnik',
    peakCs: 'Skalník',
    peakDe: 'Skalnik',
    elevation: 945,
    country: 'PL/CZ',
    isKs: true,
    isKgp: true,
    imageUrl:
      '/images/mountains/7bbd.jpeg',
  },
  {
    id: 23,
    rank: 23,
    name: 'Góry Kamienne',
    nameCs: 'Vraní hory / Javoří hory',
    nameDe: 'Steingebirge',
    peak: 'Waligóra',
    peakCs: 'Vraní hory / Javoří hory',
    peakDe: 'Steingebirge',
    elevation: 936,
    country: 'PL',
    isKs: true,
    isKgp: true,
    imageUrl: '/images/mountains/NSOFpE.jpeg',
  },
  {
    id: 24,
    rank: 24,
    name: 'Góry Opawskie',
    nameCs: 'Zlatohorská vrchovina',
    nameDe: 'Zuckmanteler Bergland',
    peak: 'Zámecký vrch',
    peakCs: 'Zámecký vrch',
    peakDe: 'Schlossberg',
    elevation: 934,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/LavBKN.jpeg',
  },
  {
    id: 25,
    rank: 25,
    name: 'Góry Stołowe',
    nameCs: 'Stolové hory',
    nameDe: 'Heuscheuergebirge',
    peak: 'Szczeliniec Wielki',
    peakCs: 'Stolová hora',
    peakDe: 'Heuscheuer',
    elevation: 919,
    country: 'PL/CZ',
    isKs: true,
    isKgp: true,
    imageUrl: '/images/mountains/M0u4F9.jpeg',
  },
  {
    id: 26,
    rank: 26,
    name: 'Góry Bialskie',
    nameCs: 'Bělské hory',
    nameDe: 'Bielengebirge',
    peak: 'Větrov',
    peakCs: 'Větrov',
    peakDe: '',
    elevation: 918,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/9hkB6P6.jpeg',
  },
  {
    id: 27,
    rank: 27,
    name: 'Góry Opawskie',
    nameCs: 'Zlatohorská vrchovina',
    nameDe: 'Zuckmanteler Bergland',
    peak: 'Biskupia Kopa',
    peakCs: 'Biskupská kupa',
    peakDe: 'Zuckmanteler Bergland',
    elevation: 890,
    country: 'PL',
    isKs: false,
    isKgp: true,
    imageUrl: '/images/mountains/K91F2O.jpeg',
  },
  {
    id: 28,
    rank: 28,
    name: 'Rudawy Janowickie',
    nameCs: 'Janovické rudohoří',
    nameDe: 'Landeshuter Kamm',
    peak: 'Wołek',
    peakCs: 'Volek',
    peakDe: 'Ochsberg',
    elevation: 878,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl:
      '/images/mountains/ac3f.jpeg',
  },
  {
    id: 29,
    rank: 29,
    name: 'Góry Wałbrzyskie',
    nameCs: 'Valbřišské hory',
    nameDe: 'Waldenburgergebirge',
    peak: 'Borowa',
    peakCs: 'Borowa',
    peakDe: 'Borowa',
    elevation: 853,
    country: 'PL',
    isKs: true,
    isKgp: false,
    imageUrl: '/images/mountains/zWfBYIM.jpeg',
  },
  {
    id: 30,
    rank: 30,
    name: 'Góry Wałbrzyskie',
    nameCs: 'Valbřišské hory',
    nameDe: 'Waldenburgergebirge',
    peak: 'Chełmiec',
    peakCs: 'Chelmec',
    peakDe: 'Chelmzberg',
    elevation: 851,
    country: 'PL',
    isKs: false,
    isKgp: true,
    imageUrl: '/images/mountains/ucSIp.jpeg',
  },
  {
    id: 31,
    rank: 31,
    name: 'Masyw Śnieżnika',
    nameCs: 'Králický Sněžník',
    nameDe: 'Glatzer Schneegebirge',
    peak: 'Igliczna',
    peakCs: 'Iglišná',
    peakDe: 'Igelberg',
    elevation: 845,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl:
      '/images/mountains/10fc.jpeg',
  },
  {
    id: 32,
    rank: 32,
    name: 'Góry Sowie',
    nameCs: 'Soví hory',
    nameDe: 'Eulengebirge',
    peak: 'Włodarz',
    peakCs: 'Vladař',
    peakDe: 'Waldenburger Berg',
    elevation: 811,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/MJrgkC.jpeg',
  },
  {
    id: 33,
    rank: 33,
    name: 'Góry Wałbrzyskie',
    nameCs: 'Valbřišské hory',
    nameDe: 'Waldenburgergebirge',
    peak: 'Gomólnik Mały',
    peakCs: 'Gomolník',
    peakDe: 'Kleiner Kammelberg',
    elevation: 807,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/ZWoNj6.jpeg',
  },
  {
    id: 34,
    rank: 34,
    name: 'Niski Jesionik',
    nameCs: 'Nízký Jeseník',
    nameDe: 'Niederes Gesenke',
    peak: 'Slunečná',
    peakCs: 'Slunečná',
    peakDe: 'Niederes Gesenke',
    elevation: 800,
    country: 'CZ',
    isKs: true,
    isKgp: false,
    imageUrl: '/images/mountains/IL8BG40.jpeg',
  },
  {
    id: 35,
    rank: 35,
    name: 'Góry Łużyckie',
    nameCs: 'Lužické hory',
    nameDe: 'Lausitzer Gebirge',
    peak: 'Luž / Lausche',
    peakCs: 'Luž',
    peakDe: 'Lausche',
    elevation: 793,
    country: 'PL/CZ',
    isKs: true,
    isKgp: false,
    imageUrl: '/images/mountains/lHvqYn.jpeg',
  },
  {
    id: 36,
    rank: 36,
    name: 'Grzbiet Jesztedzko-Kozakowski',
    nameCs: 'Ještědsko-kozákovský hřbet',
    nameDe: 'Jeschken-Kosakow-Kamm',
    peak: 'Vápenný',
    peakCs: 'Vápenný',
    peakDe: 'Kalkberg',
    elevation: 790,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/t1QBOd.jpeg',
  },
  {
    id: 37,
    rank: 37,
    name: 'Góry Izerskie',
    nameCs: 'Jizerské hory',
    nameDe: 'Isergebirge',
    peak: 'Muchov',
    peakCs: 'Muchov',
    peakDe: 'Muxberg',
    elevation: 787,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/pSVGiD.jpeg',
  },
  {
    id: 38,
    rank: 38,
    name: 'Góry Wałbrzyskie',
    nameCs: 'Valbřišské hory',
    nameDe: 'Waldenburgergebirge',
    peak: 'Wołowiec',
    peakCs: 'Volovec',
    peakDe: 'Ochsberg',
    elevation: 776,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl:
      '/images/mountains/fc81.jpeg',
  },
  {
    id: 39,
    rank: 39,
    name: 'Góry Bardzkie',
    nameCs: 'Bardské hory',
    nameDe: 'Warthagebirge',
    peak: 'Szeroka Góra',
    peakCs: 'Bardská hora',
    peakDe: 'Warthagebirge',
    elevation: 765,
    country: 'PL',
    isKs: true,
    isKgp: false,
    imageUrl: '/images/mountains/EWrGt3.jpeg',
  },
  {
    id: 40,
    rank: 40,
    name: 'Góry Bardzkie',
    nameCs: 'Bardské hory',
    nameDe: 'Warthagebirge',
    peak: 'Kłodzka Góra',
    peakCs: 'Kladská hora',
    peakDe: 'Warthagebirge',
    elevation: 757,
    country: 'PL',
    isKs: false,
    isKgp: true,
    imageUrl: '/images/mountains/41nfE6.jpeg',
  },
  {
    id: 41,
    rank: 41,
    name: 'Góry Jastrzębie',
    nameCs: 'Žacléřská vrchovina',
    nameDe: 'Habichtgebirge',
    peak: 'Žaltman',
    peakCs: 'Žaltman',
    peakDe: 'Habicht',
    elevation: 739,
    country: 'CZ',
    isKs: true,
    isKgp: false,
    imageUrl: '/images/mountains/jfNE4x.jpeg',
  },
  {
    id: 42,
    rank: 42,
    name: 'Góry Kaczawskie',
    nameCs: 'Kačavské hory',
    nameDe: 'Bober-Katzbach-Gebirge',
    peak: 'Skopiec',
    peakCs: 'Skopiec',
    peakDe: 'Skopetz',
    elevation: 724,
    country: 'PL',
    isKs: true,
    isKgp: true,
    imageUrl:
      '/images/mountains/1429.jpeg',
  },
  {
    id: 43,
    rank: 43,
    name: 'Góry Izerskie',
    nameCs: 'Jizerské hory',
    nameDe: 'Isergebirge',
    peak: 'Špičák',
    peakCs: 'Špičák',
    peakDe: 'Spitzberg',
    elevation: 724,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl:
      '/images/mountains/60ab.jpeg',
  },
  {
    id: 44,
    rank: 44,
    name: 'Góry Kaczawskie',
    nameCs: 'Kačavské hory',
    nameDe: 'Bober-Katzbach-Gebirge',
    peak: 'Baraniec',
    peakCs: 'Baraniec',
    peakDe: 'Widderberg',
    elevation: 720,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl:
      '/images/mountains/7a93.jpeg',
  },
  {
    id: 45,
    rank: 45,
    name: 'Góry Kaczawskie',
    nameCs: 'Kačavské hory',
    nameDe: 'Bober-Katzbach-Gebirge',
    peak: 'Okole',
    peakCs: 'Okole',
    peakDe: 'Ockelberg',
    elevation: 718,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/Lk2ENs.jpeg',
  },
  {
    id: 46,
    rank: 46,
    name: 'Masyw Ślęży',
    nameCs: 'Slepá hora',
    nameDe: 'Zobtengebirge',
    peak: 'Ślęża',
    peakCs: 'Slepá hora',
    peakDe: 'Zobten',
    elevation: 718,
    country: 'PL',
    isKs: true,
    isKgp: true,
    imageUrl: '/images/mountains/r3koNk.jpeg',
  },
  {
    id: 47,
    rank: 47,
    name: 'Zábřežská vrchovina',
    nameCs: 'Zábřežská vrchovina',
    nameDe: 'Hohenstädter Bergland',
    peak: 'Lázek',
    peakCs: 'Lázek',
    peakDe: 'Hohenstädter Bergland',
    elevation: 714,
    country: 'CZ',
    isKs: true,
    isKgp: false,
    imageUrl: '/images/mountains/9EMY0F.jpeg',
  },
  {
    id: 48,
    rank: 48,
    name: 'Góry Kamienne',
    nameCs: 'Vraní hory / Javoří hory',
    nameDe: 'Steingebirge',
    peak: 'Boreczna',
    peakCs: 'Borečná',
    peakDe: 'Borschener Berg',
    elevation: 710,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl:
      '/images/mountains/6940.jpeg',
  },
  {
    id: 49,
    rank: 49,
    name: 'Niski Jesionik',
    nameCs: 'Nízký Jeseník',
    nameDe: 'Niederes Gesenke',
    peak: 'Pomezí',
    peakCs: 'Pomezí',
    peakDe: '',
    elevation: 707,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/pm1F8V.jpeg',
  },
  {
    id: 50,
    rank: 50,
    name: 'Góry Bystrzyckie',
    nameCs: 'Bystřické hory',
    nameDe: 'Habelschwerdter Gebirge',
    peak: 'Kamienna Góra',
    peakCs: 'Kamienna Góra',
    peakDe: 'Steinberg',
    elevation: 704,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/ucHMKh.jpeg',
  },
  {
    id: 51,
    rank: 51,
    name: 'Góry Jastrzębie',
    nameCs: 'Žacléřská vrchovina',
    nameDe: 'Habichtgebirge',
    peak: 'Jański Wierch',
    peakCs: 'Janský vrch',
    peakDe: 'Johannisberg',
    elevation: 697,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/8sMBza.jpeg',
  },
  {
    id: 52,
    rank: 52,
    name: 'Grzbiet Jesztedzko-Kozakowski',
    nameCs: 'Ještědsko-kozákovský hřbet',
    nameDe: 'Jeschken-Kosakow-Kamm',
    peak: 'Javorník',
    peakCs: 'Javorník',
    peakDe: 'Jauerling',
    elevation: 684,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl:
      '/images/mountains/960x720_5OfVZo.jpg',
  },
  {
    id: 53,
    rank: 53,
    name: 'Góry Wałbrzyskie',
    nameCs: 'Valbřišské hory',
    nameDe: 'Waldenburgergebirge',
    peak: 'Niedźwiadki',
    peakCs: 'Medvídky',
    peakDe: 'Bärenberg',
    elevation: 629,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/q0JBO6e.jpeg',
  },
  {
    id: 54,
    rank: 54,
    name: 'Masyw Śnieżnika',
    nameCs: 'Králický Sněžník',
    nameDe: 'Glatzer Schneegebirge',
    peak: 'Wapniarka',
    peakCs: 'Wapniarka',
    peakDe: 'Kalkberg',
    elevation: 532,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl:
      '/images/mountains/d53d.jpeg',
  },
  {
    id: 55,
    rank: 55,
    name: 'Góry Stołowe',
    nameCs: 'Stolové hory',
    nameDe: 'Heuscheuergebirge',
    peak: 'Guzowata',
    peakCs: 'Guzowata',
    peakDe: 'Gusseberg',
    elevation: 492,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/NY4DV3.jpeg',
  },
];
