export interface SudetenRange {
  id: number;
  rank: number;
  rangeName: string;
  foreignRangeName?: string;
  peakName: string;
  foreignPeakName?: string;
  peakHeight: number;
  country: string;
  isKs: boolean; // Korona Sudetów
  isKgp: boolean; // Korona Gór Polski
  imageUrl: string; // URL zdjęcia szczytu
  description: string; // Opis szczytu
  // Special additional names for specific peaks (e.g., Góry Łużyckie Luž)
  additionalRangeNameGerman?: string;
  additionalRangeNameCzech?: string;
  additionalPeakNameCzech?: string;
  additionalPeakNameGerman?: string;
}

// Dane wszystkich szczytów uporządkowane od najwyższego do najniższego
export const sudetenRanges: SudetenRange[] = [
  {
    id: 1,
    rank: 1,
    rangeName: 'Karkonosze',
    foreignRangeName: 'Krkonoše',
    peakName: 'Śnieżka',
    foreignPeakName: 'Sněžka',
    peakHeight: 1603,
    country: 'PL/CZ',
    isKs: true,
    isKgp: true,
    imageUrl: '/images/mountains/f3RVVv.jpeg',
    description:
      '• Historyczna kaplica św. Wawrzyńca z XVII wieku na wierzchołku\n• Polska stacja meteorologiczna na szczycie\n• Wysokogórskie Obserwatorium Meteorologiczne przypomina "latające spodki"\n• Mgła utrzymuje się przez ponad 300 dni w roku, sprzyjając zjawiskom jak widmo Brockenu czy ognie św. Elma\n• Najwyżej położona czeska placówka pocztowa\n• Rekordowe podmuchy wiatru osiągnęły 288 km/h',
  },
  {
    id: 2,
    rank: 2,
    rangeName: 'Wysoki Jesionik',
    foreignRangeName: 'Hrubý Jeseník',
    peakName: 'Praděd',
    foreignPeakName: 'Pradziad',
    peakHeight: 1491,
    country: 'CZ',
    isKs: true,
    isKgp: false,
    imageUrl: '/images/mountains/HIydYU.jpeg',
    description:
      '• Wieża telewizyjna o wysokości 162 metrów z restauracją - najwyżej położony punkt w Czechach\n• Obszar znany jako "Morawski lodowiec" ze względu na obfite opady śniegu\n• W granicach Narodowego Rezerwatu Przyrody Pradziad chroniącego alpejskie ekosystemy i rzadkie gatunki\n• Unikalne mroźne rozpadliny Tabulové skály z charakterystyczną górską florą i fauną\n• W pobliżu źródła rzeki Morawy',
  },
  {
    id: 3,
    rank: 3,
    rangeName: 'Masyw Śnieżnika',
    foreignRangeName: 'Králický Sněžník',
    peakName: 'Śnieżnik',
    foreignPeakName: 'Králický Sněžník',
    peakHeight: 1423,
    country: 'PL/CZ',
    isKs: true,
    isKgp: true,
    imageUrl: '/images/mountains/21iGzM.jpeg',
    description:
      '• Najwyższy punkt kraju pardubickiego\n• Nowa wieża widokowa z 2022 roku - poprzednia wieża z końca XIX wieku została zburzona w 1973 roku\n• Niedaleko Trojmezní kámen - historyczny punkt styku Czech, Moraw i hrabstwa Kłodzkiego\n• Spotykają się tutaj trzy główne europejskie działy wodne prowadzące do Morza Czarnego, Północnego i Bałtyckiego\n• Długotrwała pokrywa śnieżna utrzymująca się nawet do 8 miesięcy w roku',
  },
  {
    id: 4,
    rank: 4,
    rangeName: 'Karkonosze',
    foreignRangeName: 'Krkonoše',
    peakName: 'Skalny Stół',
    foreignPeakName: 'Skalní stůl',
    peakHeight: 1284,
    country: 'PL/CZ',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/HhqXgh.jpeg',
    description:
      '• Rozległy, płaski wierzchołek przypominający stół\n• Bogate złoża kamieni szlachetnych, zwłaszcza granatów\n• Ruiny dawnej osady Forstbauden, zlikwidowanej w związku z poszukiwaniami uranu\n• Fragment terenu zamknięty w celu ochrony zagrożonych gatunków',
  },
  {
    id: 5,
    rank: 5,
    rangeName: 'Karkonosze',
    foreignRangeName: 'Krkonoše',
    peakName: 'Łysocina',
    foreignPeakName: 'Lysečinská hora',
    peakHeight: 1188,
    country: 'PL/CZ',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/hyN3UJ.jpeg',
    description:
      '• Najwyższy szczyt Grzbietu Lasockiego - najbardziej na wschód wysuniętej części Karkonoszy\n• Stanowi główny europejski dział wodny\n• W pobliżu górna stacja czeskiego wyciągu narciarskiego z kamerą dla Czeskiej Telewizji\n• Dawniej zalesione zbocza przekształcają się w polany',
  },
  {
    id: 6,
    rank: 6,
    rangeName: 'Góry Złote',
    foreignRangeName: 'Rychlebské hory',
    peakName: 'Smrk',
    foreignPeakName: 'Smrek',
    peakHeight: 1127,
    country: 'CZ',
    isKs: true,
    isKgp: false,
    imageUrl: '/images/mountains/lUpg9J.jpeg',
    description:
      '• Należy do najbardziej płaskich szczytów w Sudetach\n• Nie przebiega przez niego żaden szlak turystyczny - najbliżej czerwona ścieżka około 100 m od wierzchołka\n• Chroniony obszar torfowiskowy Malení z roślinnością bagienną\n• W pobliżu historyczny trójstyk Moraw, Śląska i Polski',
  },
  {
    id: 7,
    rank: 7,
    rangeName: 'Góry Izerskie',
    peakName: 'Wysoka Kopa',
    peakHeight: 1127,
    country: 'PL',
    isKs: true,
    isKgp: true,
    imageUrl: '/images/mountains/gR8BeBW.jpeg',
    description:
      '• Przez szczyt nie prowadzi żaden oznakowany szlak turystyczny - najbliżej czerwony szlak około 300 metrów na północ\n• W rejonie największy w Polsce kompleks torfowisk górskich z unikalną roślinnością i małymi jeziorkami\n• W pobliżu dawne wyrobisko kwarcu - kopalnia Stanisław, najwyżej położona kopalnia odkrywkowa w Polsce\n• Dostęp na sam szczyt ograniczony ze względu na ochronę cietrzewia\n• W okolicy Hala Izerska - polski biegun zimna, gdzie zanotowano nawet -45°C',
  },
  {
    id: 8,
    rank: 8,
    rangeName: 'Góry Izerskie',
    foreignRangeName: 'Jizerské hory',
    peakName: 'Smrk',
    foreignPeakName: 'Smrek',
    peakHeight: 1124,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/IXDEH5.jpeg',
    description:
      '• Wieża widokowa z 2003 roku oraz pomnik Körnera na szczycie\n• Przez długi czas przecinały się tutaj granice Czech, Łużyc i Śląska - góra znana z historycznych sporów granicznych\n• Na południowych stokach bierze początek rzeka Jizera\n• W okolicy rezerwat przyrody Klečoviště\n• Góra znana z katastrof lotniczych',
  },
  {
    id: 9,
    rank: 9,
    rangeName: 'Góry Orlickie',
    foreignRangeName: 'Orlické hory',
    peakName: 'Velká Deštná',
    foreignPeakName: 'Wielka Desztna',
    peakHeight: 1116,
    country: 'CZ',
    isKs: true,
    isKgp: false,
    imageUrl: '/images/mountains/ePxDlu.jpeg',
    description:
      '• Nowoczesna wieża widokowa z 2019 roku o wysokości 17,34 metra, zastępująca wcześniejsze drewniane konstrukcje\n• Projekt wieży inspirowany warunkami klimatycznymi regionu - ukośne drewniane elementy elewacji symbolizują deszcz i wiatr\n• W pobliżu torfowisko Jelení lázeň między Velką a Małą Deštną z unikalną florą bagienną\n• Około pół kilometra poniżej szczytu przy zielonym szlaku źródełko z doskonałą wodą i pięknym widokiem na okolicę\n• W sezonie dostępna restauracja przy skrzyżowaniu szlaków turystycznych',
  },
  {
    id: 10,
    rank: 10,
    rangeName: 'Góry Bialskie',
    foreignRangeName: 'Bělské hory',
    peakName: 'Rudawiec',
    foreignPeakName: 'Polská hora',
    peakHeight: 1112,
    country: 'PL/CZ',
    isKs: true,
    isKgp: true,
    imageUrl: '/images/mountains/90RIpm.jpeg',
    description:
      '• Najbardziej wysunięty na północ punkt Moraw\n• Trzeci co do wysokości szczyt Gór Bialskich, wybrany jako reprezentant pasma ze względu na dostępność znakowanych szlaków\n• Ze stoków rozpościerają się panoramy na Masyw Śnieżnika',
  },
  {
    id: 11,
    rank: 11,
    rangeName: 'Góry Orlickie',
    foreignRangeName: 'Orlické hory',
    peakName: 'Orlica',
    foreignPeakName: 'Vrchmezí',
    peakHeight: 1084,
    country: 'PL/CZ',
    isKs: false,
    isKgp: true,
    imageUrl: '/images/mountains/HC8l6H.jpeg',
    description:
      '• Dawniej stało tu popularne schronisko z wieżą widokową, które spłonęło w 1946 roku\n• Od 2020 roku nowa drewniana wieża widokowa o wysokości 25,5 metra\n• Szczyt odwiedzali znani goście: cesarz Józef II, późniejszy prezydent USA John Quincy Adams oraz Fryderyk Chopin\n• Pomnik upamiętniający historyczne wizyty znanych osobistości\n• Leży na europejskim dziale wodnym oddzielającym zlewiska Morza Bałtyckiego i Morza Północnego',
  },
  {
    id: 12,
    rank: 12,
    rangeName: 'Góry Izerskie',
    peakName: 'Wysoki Kamień',
    peakHeight: 1058,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/XW0Fwq.jpeg',
    description:
      '• Pierwsze schronisko wybudowane w 1837 roku przez rodzinę Schaffgotschów\n• Schronisko spłonęło w 1882 roku, ale zostało odbudowane jeszcze w tym samym roku\n• Po II wojnie światowej obiekt popadł w ruinę i został rozebrany\n• W 1996 roku teren zakupiony przez rodzinę Gołbów ze Szklarskiej Poręby, która odbudowała schronisko\n• Kamienna wieża widokowa ukończona w 2023 roku\n• Ciekawe formacje skalne na szczycie i grzbiecie',
  },
  {
    id: 13,
    rank: 13,
    rangeName: 'Góry Sowie',
    peakName: 'Wielka Sowa',
    peakHeight: 1015,
    country: 'PL',
    isKs: true,
    isKgp: true,
    imageUrl: '/images/mountains/xPoV6s.jpeg',
    description:
      '• Historyczna żelbetowa wieża widokowa z 1906 roku, znana wcześniej jako wieża Bismarcka\n• Wieża była kilkakrotnie odnawiana po II wojnie światowej i ponownie otwarta po gruntownej renowacji w 2008 roku\n• Wieża była w remoncie do 2023 roku\n• Wyciąg narciarski w okolicy nieczynny od 2011 roku\n• Leży w Parku Krajobrazowym Gór Sowich',
  },
  {
    id: 14,
    rank: 14,
    rangeName: 'Grzbiet Jesztedzko-Kozakowski',
    foreignRangeName: 'Ještědsko-kozákovský hřbet',
    peakName: 'Ještěd',
    foreignPeakName: 'Jeszted',
    peakHeight: 1012,
    country: 'CZ',
    isKs: true,
    isKgp: false,
    imageUrl: '/images/mountains/WNtH0o.jpeg',
    description:
      '• Unikalna wieża telewizyjna i hotel zaprojektowane przez architekta Karela Hubáčka mają kształt hiperboloidy - ukończone w 1973 roku\n• W 1969 roku projekt Hubáčka otrzymał prestiżową nagrodę Perreta od Międzynarodowej Unii Architektów\n• Pierwsze schronisko na szczycie powstało w 1844 roku, a w 1963 roku spłonęło, co doprowadziło do budowy obecnej wieży\n• W sierpniu 1968 roku podczas interwencji wojsk Układu Warszawskiego działało tu Wolne Studio Północ nadające audycje informacyjne',
  },
  {
    id: 15,
    rank: 15,
    rangeName: 'Góry Hanuszowickie',
    foreignRangeName: 'Hanušovická vrchovina',
    peakName: 'Jeřáb',
    foreignPeakName: 'Jerab',
    peakHeight: 1003,
    country: 'CZ',
    isKs: true,
    isKgp: false,
    imageUrl: '/images/mountains/2qKNS.jpeg',
    description:
      '• Platforma widokowa z widokiem na Králický Sněžník\n• Leży na historycznej i współczesnej granicy między Czechami a Morawami\n• Przez szczyt przebiega europejski dział wodny między dorzeczami Łaby i Dunaju\n• Na zachodnim zboczu źródło Tiché Orlice\n• W pobliżu źródła Rudolfův pramen wznosi się kaplica Świętej Trójcy',
  },
  {
    id: 16,
    rank: 16,
    rangeName: 'Góry Złote',
    foreignRangeName: 'Rychlebské hory',
    peakName: 'Kowadło',
    foreignPeakName: 'Kovadlina',
    peakHeight: 989,
    country: 'PL/CZ',
    isKs: false,
    isKgp: true,
    imageUrl: '/images/mountains/Dmj5ru.jpeg',
    description:
      '• Dolina Białej Lądeckiej u podnóża była niegdyś szlakiem handlowym zwanym Drogą Solną - przewożono tędy sól z morawskich kopalni soli do Kłodzka\n• Porasta go świerkowy las i gnejsowe skałki\n• Leży na umownej granicy pomiędzy Górami Złotymi a Bialskimi',
  },
  {
    id: 17,
    rank: 17,
    rangeName: 'Góry Bystrzyckie',
    peakName: 'Jagodna Północna',
    peakHeight: 985,
    country: 'PL',
    isKs: true,
    isKgp: false,
    imageUrl: '/images/mountains/c11b.jpeg',
    description:
      '• Północny wierzchołek masywu Jagodnej, oddzielony od głównego szczytu\n• Nie jest oznakowany szlakami turystycznymi i nie posiada infrastruktury\n• Na mapach topograficznych geoportalu błędnie oznaczony jako "Sasanka"\n• Nazwa "Jagodna Północna" jest obecnie niestandaryzowana - trwają prace Komisji Nazewniczej przy Państwowym Rejestrze Nazw\n• Zaliczana do Diademu Polskich Gór',
  },
  {
    id: 18,
    rank: 18,
    rangeName: 'Góry Bystrzyckie',
    peakName: 'Jagodna',
    peakHeight: 977,
    country: 'PL',
    isKs: false,
    isKgp: true,
    imageUrl: '/images/mountains/h4Un27.jpeg',
    description:
      '• 23-metrowa wieża widokowa wybudowana w 2019 roku\n• Z wieży roztaczają się panoramy na Masyw Śnieżnika, Góry Orlickie, Bystrzyckie i Stołowe, a także odległe Karkonosze\n• Powszechnie uznawana za najwyższy szczyt pasma w ujęciu turystycznym - wyższa Jagodna Północna (985 m) nie posiada oznakowanych szlaków',
  },
  {
    id: 19,
    rank: 19,
    rangeName: 'Góry Opawskie',
    foreignRangeName: 'Zlatohorská vrchovina',
    peakName: 'Příčný vrch',
    foreignPeakName: 'Góra Poprzeczna',
    peakHeight: 975,
    country: 'CZ',
    isKs: true,
    isKgp: false,
    imageUrl: '/images/mountains/ACbNtQ.jpeg',
    description:
      '• Ma formę płaskiego grzbietu o długości około 3 km, porośniętego głównie lasami świerkowymi z domieszką buka\n• Od średniowiecza była miejscem intensywnej eksploatacji złota oraz innych metali (ołów, miedź, piryt)\n• Kopalnie zostały zamknięte w grudniu 1993 roku, pozostawiając liczne szyby i chodniki o łącznej długości około 120 km\n• W okolicy ruiny zamku Edelštejn oraz ścieżka dydaktyczna o tematyce górniczej prowadząca ze Zlatých Hor na szczyt',
  },
  {
    id: 20,
    rank: 20,
    rangeName: 'Karkonosze',
    foreignRangeName: 'Krkonoše',
    peakName: 'Hvězda',
    foreignPeakName: 'Hvězda',
    peakHeight: 959,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/llLHyl.jpeg',
    description:
      '• 24-metrowa neogotycka wieża widokowa Štěpánka z 1892 roku, zbudowana z cegły i piaskowca\n• Leży na granicy Gór Izerskich i Karkonoskiego Parku Narodowego\n• W przeszłości góra nosiła inne nazwy: Buková hora oraz Štěpánova výšina',
  },
  {
    id: 21,
    rank: 21,
    rangeName: 'Rudawy Janowickie',
    peakName: 'Skalnik',
    peakHeight: 945,
    country: 'PL',
    isKs: true,
    isKgp: true,
    imageUrl: '/images/mountains/7bbd.jpeg',
    description:
      '• Składa się z dwóch wierzchołków - wyższego zalesionego i niższego Ostra Mała z platformą widokową\n• Charakterystyczne formacje skalne "Konie Apokalipsy" na południowym stoku góry\n• Znajduje się tu drewniana budka z pieczątką Korony Gór Polski\n• Ruiny starej wieży widokowej na szczycie\n• U podnóża miejscowości Strużnica i Czarnów ze schroniskiem „Czartak"',
  },
  {
    id: 22,
    rank: 22,
    rangeName: 'Rudawy Janowickie',
    peakName: 'Ostra Mała',
    peakHeight: 945,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/OMquq.jpeg',
    description:
      '• Platforma widokowa dostępna stopniami wykutymi w skale w 1886 roku\n• Fantazyjne formacje skalne na wierzchołku tworzą charakterystyczny krajobraz\n• Położona w Rudawskim Parku Krajobrazowym chroniącym unikalne wartości przyrodnicze\n• Często mylona z sąsiednim Skalnikiem, który jest najwyższym szczytem Rudaw Janowickich',
  },
  {
    id: 23,
    rank: 23,
    rangeName: 'Góry Kamienne',
    peakName: 'Waligóra',
    peakHeight: 936,
    country: 'PL',
    isKs: true,
    isKgp: true,
    imageUrl: '/images/mountains/NSOFpE.jpeg',
    description:
      '• Dawniej znajdowała się tutaj wieża widokowa\n• Masyw z łagodnym zboczem południowym i bardzo stromymi pozostałymi zboczami\n• Szczyt w całości zalesiony, co ogranicza widoki z wierzchołka\n• Popularna wśród turystów dzięki bliskości Przełęczy Trzech Dolin z dostępnymi szlakami, schroniskiem i możliwościami uprawiania sportów zimowych',
  },
  {
    id: 24,
    rank: 24,
    rangeName: 'Góry Opawskie',
    foreignRangeName: 'Zlatohorská vrchovina',
    peakName: 'Zámecký vrch',
    peakHeight: 934,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/LavBKN.jpeg',
    description:
      '• Ruiny zamku Koberštejn zbudowanego pod koniec XIII wieku\n• Zamek został opuszczony w XIV wieku i miał za zadanie chronić szlak handlowy między Zlatými Horami a Vrbnem\n• Przez szczyt przebiega zielony szlak turystyczny prowadzący do pomnika żołnierzy radzieckich\n• Widoki na okoliczne pasmo Medvědská hornatina',
  },
  {
    id: 25,
    rank: 25,
    rangeName: 'Góry Stołowe',
    peakName: 'Szczeliniec Wielki',
    peakHeight: 919,
    country: 'PL/CZ',
    isKs: true,
    isKgp: true,
    imageUrl: '/images/mountains/M0u4F9.jpeg',
    description:
      '• Wejście prowadzi przez 665 kamiennych schodów ułożonych na przełomie XVIII i XIX wieku przez Franza Pabla, ówczesnego sołtysa Karłowa\n• Labirynt skalny z fantazyjnymi formacjami skalnymi, takimi jak "Kołyska Księżniczki Emilii" i "Serce Ducha Górskiego"\n• "Piekiełko" – wąska szczelina skalna o długości około 100 metrów i głębokości blisko 20 metrów, w której nawet latem panuje niska temperatura\n• Nagrywano tu sceny do filmu "Opowieści z Narnii"\n• Atrakcja znana od 1576 roku',
  },
  {
    id: 26,
    rank: 26,
    rangeName: 'Góry Złote',
    foreignRangeName: 'Rychlebské hory',
    peakName: 'Větrov',
    peakHeight: 918,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/9hkB6P6.jpeg',
    description:
      '• Dalimilova rozhledna otwarta w 2021 roku - kamienna wieża widokowa o wysokości 34 metrów\n• Wieża jest wierną repliką historycznej wieży cesarza Wilhelma I, która stała na Śnieżniku w latach 1899–1973\n• Na szczyt wieży prowadzi 170 schodów, a platformy widokowe znajdują się na wysokościach 17 i 28 metrów\n• W pobliżu popularne schronisko turystyczne Paprsek',
  },
  {
    id: 27,
    rank: 27,
    rangeName: 'Góry Opawskie',
    foreignRangeName: 'Zlatohorská vrchovina',
    peakName: 'Biskupia Kopa',
    foreignPeakName: 'Biskupská kupa',
    peakHeight: 890,
    country: 'PL/CZ',
    isKs: false,
    isKgp: true,
    imageUrl: '/images/mountains/K91F2O.jpeg',
    description:
      '• 18-metrowa kamienna wieża widokowa z 1898 roku, wybudowana z okazji 50-lecia panowania cesarza Franciszka Józefa I\n• Najstarsza wieża widokowa w Jesionikach, oferująca panoramę na Pradziada i Zlatý chlum\n• Schronisko PTTK "Pod Biskupią Kopą" z 1925 roku jest jedynym schroniskiem turystycznym w Górach Opawskich\n• Najwyższy punkt województwa opolskiego\n• W okolicy Gwarkowa Perć - 11-metrowa drabina skalna na jednym z szlaków\n• Dostępna szlakami turystycznymi ze Zlatých Hor i Petrovic',
  },
  {
    id: 28,
    rank: 28,
    rangeName: 'Rudawy Janowickie',
    peakName: 'Wołek',
    peakHeight: 878,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/ac3f.jpeg',
    description:
      '• Krzyż poświęcony Janowi Pawłowi II na szczycie\n• W przeszłości szczyt był w całości zalesiony, obecnie po wycince drzew rozpościerają się widoki na Kotlinę Jeleniogórską, Góry Sokole oraz Karkonosze\n• Leży w Rudawskim Parku Krajobrazowym chroniącym unikalne wartości przyrodnicze\n• Charakteryzuje się bogatą florą – lasami świerkowymi, mieszanymi oraz kosodrzewiną',
  },
  {
    id: 29,
    rank: 29,
    rangeName: 'Góry Wałbrzyskie',
    peakName: 'Borowa',
    peakHeight: 853,
    country: 'PL',
    isKs: true,
    isKgp: false,
    imageUrl: '/images/mountains/zWfBYIM.jpeg',
    description:
      '• Nowoczesna wieża widokowa z 2017 roku o wysokości 16,5 metra zaprojektowana przez Zbigniewa Mazija\n• Wieża ma unikalny kształt hiperboloidy jednopowłokowej\n• Charakterystyczna trapezoidalna forma góry widoczna z Kotliny Wałbrzyskiej\n• Zbudowana ze skał wylewnych (ryolity, trachybazalty) będących świadectwem dawnej działalności wulkanicznej\n• Z platformy widokowej przy dobrej pogodzie widać wrocławski Sky Tower\n• Leży w Parku Krajobrazowym Sudetów Wałbrzyskich',
  },
  {
    id: 30,
    rank: 30,
    rangeName: 'Góry Wałbrzyskie',
    peakName: 'Chełmiec',
    peakHeight: 851,
    country: 'PL',
    isKs: false,
    isKgp: true,
    imageUrl: '/images/mountains/ucSIp.jpeg',
    description:
      '• Zabytkowa kamienna wieża widokowa z końca XIX wieku\n• 45-metrowy Krzyż Milenijny będący zwieńczeniem Boguszowskiej Drogi Krzyżowej Trudu Górniczego\n• Charakterystyczny kopulasty kształt widoczny nawet z odległego o około 70 km Wrocławia\n• Obszar objęty ochroną Natura 2000 z unikalnymi siedliskami leśnymi, w tym buczynami sudeckimi\n• 69-metrowy stalowy maszt radiowo-telewizyjny na szczycie\n• W pobliżu szczytu oświetlony krzyż, będący celem szlaków pielgrzymkowych',
  },
  {
    id: 31,
    rank: 31,
    rangeName: 'Masyw Śnieżnika',
    peakName: 'Igliczna',
    peakHeight: 845,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/10fc.jpeg',
    description:
      '• Na południowym zboczu Sanktuarium Matki Bożej Śnieżnej z kościołem z lat 1781-1782\n• Historia sanktuarium sięga 1750 roku, kiedy umieszczono tu figurę Matki Bożej z Mariazell w Austrii\n• W 1775 roku wichura obaliła drzewo pod figurą, która ocalała - zdarzenie uznano za cud\n• Schronisko "Na Iglicznej" powstało w 1880 roku jako gospoda "Maria Schnee" dla pielgrzymów\n• W partii szczytowej skalny grzebień z gnejsów wyrastający z rumowiska skalnego\n• Otoczona Śnieżnickim Parkiem Krajobrazowym',
  },
  {
    id: 32,
    rank: 32,
    rangeName: 'Góry Sowie',
    peakName: 'Włodarz',
    peakHeight: 811,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/MJrgkC.jpeg',
    description:
      '• Podczas II wojny światowej znajdował się tutaj obóz pracy Wolfsberg, będący częścią kompleksu więziennego "Riese" - jednego z największych projektów budowlanych III Rzeszy\n• Około 3000 więźniów, głównie Żydów, było zmuszanych do budowy tuneli w nieludzkich warunkach w latach 1943-1945\n• W obozie zmarło 612 osób - obecnie fundamenty w lesie przypominają o tej tragedii\n• Część podziemi kompleksu Riese jest udostępniona do zwiedzania, w tym unikalna trasa z przejściem łodzią po zalanych korytarzach\n• Zaliczany do Diademu Polskich Gór',
  },
  {
    id: 33,
    rank: 33,
    rangeName: 'Góry Wałbrzyskie',
    peakName: 'Gomólnik Mały',
    peakHeight: 807,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/ZWoNj6.jpeg',
    description:
      '• Nowoczesny taras widokowy otwarty w kwietniu 2023 roku oferujący panoramiczne widoki na okoliczne pasma\n• Z tarasu widokowego przy dobrej pogodzie widać Sky Tower we Wrocławiu oddalony o około 70 km\n• Leży w Parku Krajobrazowym Sudetów Wałbrzyskich chroniącym wartości przyrodnicze regionu\n• Porasta go las świerkowy charakterystyczny dla tego obszaru Sudetów',
  },
  {
    id: 34,
    rank: 34,
    rangeName: 'Niski Jesionik',
    foreignRangeName: 'Nízký Jeseník',
    peakName: 'Slunečná',
    peakHeight: 802,
    country: 'CZ',
    isKs: true,
    isKgp: false,
    imageUrl: '/images/mountains/IL8BG40.jpeg',
    description:
      '• Najwyższy szczyt Slunečné vrchoviny, będącej częścią Niskiego Jesionika\n• Zbudowana ze skał karbońskich - łupków i piaskowców\n• Charakterystyczna wieża telekomunikacyjna stanowiąca punkt orientacyjny\n• W wyniku suszy w 2015 roku oraz plagi kornika lasy znacznie przerzedzone, co odsłoniło widoki na Moravský Beroun i Hrubý Jeseník\n• Na stoku rezerwat przyrody Panské louky chroniący rzadkie lasy torfowiskowe',
  },
  {
    id: 35,
    rank: 35,
    rangeName: 'Góry Łużyckie',
    foreignRangeName: 'Lužické hory / Lausitzer Gebirge',
    peakName: 'Luž',
    foreignPeakName: 'Luz',
    peakHeight: 793,
    country: 'DE/CZ',
    isKs: true,
    isKgp: false,
    imageUrl: '/images/mountains/lHvqYn.jpeg',
    description:
      '• Charakterystyczny stożkowy kształt wyróżnia szczyt w krajobrazie regionu\n• Pozostałości historycznej chaty oraz ogólnodostępna wieża widokowa na szczycie\n• Obszar wokół szczytu jest chronionym rezerwatem przyrody o bogatej florze i faunie\n• Na południowo-wschodnich stokach ośrodek narciarski Snowpark Luž\n• Najbliższe punkty gastronomiczne znajdują się w Chata Pod Luží i Lužická bouda',
    additionalRangeNameGerman: 'Lausitzer Gebirge',
    additionalRangeNameCzech: 'Lužické hory',
    additionalPeakNameCzech: 'Luz',
    additionalPeakNameGerman: 'Lausche',
  },
  {
    id: 36,
    rank: 36,
    rangeName: 'Grzbiet Jesztedzko-Kozakowski',
    foreignRangeName: 'Ještědsko-kozákovský hřbet',
    peakName: 'Vápenný',
    peakHeight: 790,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/t1QBOd.jpeg',
    description:
      '• Rezerwat przyrody Velký Vápenný chroni cenne buczyny i lasy żwirowe\n• Na zachodnim zboczu znajduje się opuszczony kamieniołom z Jaskinią Zachodnią\n• Pozostałości umocnień z czasów I Republiki Czeskiej\n• Ważne stanowisko paleontologiczne\n• Schronienie dla nietoperzy',
  },
  {
    id: 37,
    rank: 37,
    rangeName: 'Góry Izerskie',
    foreignRangeName: 'Jizerské hory',
    peakName: 'Muchov',
    peakHeight: 787,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/pSVGiD.jpeg',
    description:
      '• Skalisty szczyt z telekomunikacyjnym nadajnikiem oferujący panoramiczne widoki\n• Według miejscowych legend jest schronieniem ducha Gór Izerskich - Muhy oraz ukrytym skarbem rozbójników\n• Grzbietowa droga prowadząca przez szczyt została wybudowana przed I wojną światową\n• Położony między punktami widokowymi Černá studnice i Terezínka',
  },
  {
    id: 38,
    rank: 38,
    rangeName: 'Góry Wałbrzyskie',
    peakName: 'Wołowiec',
    peakHeight: 776,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/fc81.jpeg',
    description:
      '• Powulkaniczne wzniesienie będące częścią trójwierzchołkowego masywu wraz z Małym Wołowcem (720 m) i Kozłem (774 m)\n• Na wierzchołku dominują buki w lesie regla dolnego\n• Pod północnym zboczem Małego Wołowca przebiegają dwa najdłuższe w Polsce tunele kolejowe na linii Wałbrzych Podgórze – Jedlina-Zdrój o długości 1560 m i 1611 m\n• Leży w Parku Krajobrazowym Sudetów Wałbrzyskich',
  },
  {
    id: 39,
    rank: 39,
    rangeName: 'Góry Bardzkie',
    peakName: 'Szeroka Góra',
    peakHeight: 765,
    country: 'PL',
    isKs: true,
    isKgp: false,
    imageUrl: '/images/mountains/EWrGt3.jpeg',
    description:
      '• W przeszłości za najwyższy szczyt Gór Bardzkich uważano Kłodzką Górę (757 m), jednak najnowsze pomiary wykazały, że to Szeroka Góra jest najwyższym wzniesieniem pasma\n• Na szczyt nie prowadzi oznakowany szlak turystyczny - dostępna jest leśna ścieżka odchodząca od żółtego szlaku prowadzącego na Kłodzką Górę\n• Na szczycie znak geodezyjny\n• Otoczona lasami świerkowymi i bukowymi',
  },
  {
    id: 40,
    rank: 40,
    rangeName: 'Góry Bardzkie',
    peakName: 'Kłodzka Góra',
    peakHeight: 757,
    country: 'PL',
    isKs: false,
    isKgp: true,
    imageUrl: '/images/mountains/41nfE6.jpeg',
    description:
      '• Drugi co do wysokości szczyt Gór Bardzkich - przez wiele lat uważano ją za najwyższy punkt pasma\n• Stalowa wieża widokowa z 2020 roku o wysokości 34,5 metra z czterema platformami widokowymi\n• Obecnie uznaje się, że wyższa jest sąsiednia Szeroka Góra (765 m), jednak to Kłodzka Góra posiada infrastrukturę turystyczną\n• W noc świętojańską organizowane są tutaj popularne nocne wędrówki\n• Porośnięta świerkowym lasem',
  },
  {
    id: 41,
    rank: 41,
    rangeName: 'Góry Jastrzębie',
    foreignRangeName: 'Jestřebí hory',
    peakName: 'Žaltman',
    peakHeight: 740,
    country: 'CZ',
    isKs: true,
    isKgp: false,
    imageUrl: '/images/mountains/jfNE4x.jpeg',
    description:
      '• Nowa wieża widokowa otwarta 24 września 2020 roku, dokładnie 53 lata po inauguracji poprzedniej konstrukcji\n• Wieża ma 25 metrów wysokości, platforma widokowa znajduje się na wysokości 23,5 metra, na którą prowadzą 122 schody\n• Z wieży roztacza się panoramiczny widok na Karkonosze, Skalny Miasto Adršpach i Teplice oraz dalsze pasma górskie\n• Obszar bogaty w zabytkowe kopalnie i fortyfikacje z okresu przed II wojną światową\n• Do szczytu prowadzi zielony szlak turystyczny i trasa rowerowa',
  },
  {
    id: 42,
    rank: 42,
    rangeName: 'Góry Kaczawskie',
    peakName: 'Skopiec',
    peakHeight: 724,
    country: 'PL',
    isKs: true,
    isKgp: true,
    imageUrl: '/images/mountains/1429.jpeg',
    description:
      '• Charakteryzuje się łagodnym, kopulastym kształtem wierzchołka porośniętym lasem mieszanym ze świerkiem\n• Zbocza częściowo zajmują łąki i pola, co nadaje górze charakterystyczny wygląd\n• Budowa geologiczna obejmuje łupki, marmury i zieleńce - pozostałości dawnych wylewów wulkanicznych i osadów morskich\n• Leży w Parku Krajobrazowym "Chełmy" chroniącym unikalne wartości przyrodnicze regionu',
  },
  {
    id: 43,
    rank: 43,
    rangeName: 'Góry Izerskie',
    foreignRangeName: 'Jizerské hory',
    peakName: 'Špičák',
    peakHeight: 724,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/60ab.jpeg',
    description:
      '• Chroniony w rezerwacie przyrody Jizerskohorské bučiny, który w 2021 roku został wpisany na listę światowego dziedzictwa UNESCO jako pierwsza naturalna lokalizacja w Czechach\n• Na skalisty wierzchołek prowadzą metalowe schody o długości 70 metrów, wyremontowane w 2006 roku\n• Przebiega przez niego ścieżka dydaktyczna "Oldřichovské háje a skály"\n• Na południowo-wschodnim zboczu pomnik drwala Geisslera, który tragicznie zginął w tym miejscu',
  },
  {
    id: 44,
    rank: 44,
    rangeName: 'Góry Kaczawskie',
    peakName: 'Baraniec',
    peakHeight: 720,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/7a93.jpeg',
    description:
      '• Charakteryzuje się łagodną, kopulastą formą z słabo wyodrębnionym wierzchołkiem\n• W części szczytowej występują skałki i blokowiska z łupków, marmurów i diabazów - pozostałość dawnych wulkanicznych i morskich osadów\n• Zbocza porasta mieszany las ze świerkiem i dębem\n• Wyróżnia się spokojnym krajobrazem z łąkami i polami na niższych stokach\n• Leży niedaleko Skopca',
  },
  {
    id: 45,
    rank: 45,
    rangeName: 'Góry Kaczawskie',
    peakName: 'Okole',
    peakHeight: 718,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/Lk2ENs.jpeg',
    description:
      '• Tworzy rozległy masyw razem z Leśniakiem\n• Zbudowany ze skał metamorficznych - zieleńców i łupków zieleńcowych\n• Drewniana platforma widokowa oraz wiata turystyczna wybudowane w 2018 roku\n• Z platformy widokowej rozciągają się panoramy na Łysą Górę, Rudawy Janowickie, Karkonosze oraz przy dobrej widoczności Szczeliniec Wielki\n• W 2019 roku oddano do użytku Kaczawskie Single Tracki - sieć tras rowerowych, z których dwie przebiegają przez masyw Okola\n• Należy do Korony Gór Dolnego Śląska',
  },
  {
    id: 46,
    rank: 46,
    rangeName: 'Masyw Ślęży',
    peakName: 'Ślęża',
    peakHeight: 718,
    country: 'PL',
    isKs: true,
    isKgp: true,
    imageUrl: '/images/mountains/r3koNk.jpeg',
    description:
      '• Od wieków miejsce kultu - od pogańskich rytuałów po średniowieczny klasztor\n• Unikatowe formacje skalne i rzeźby kultowe z czasów przedchrześcijańskich\n• Bogata historia geologiczna - pozostałość prehistorycznego dna oceanicznego\n• Na szczycie znajduje się wieża widokowa\n• Wyróżnia się imponującą wysokością względną ponad 500 metrów\n• Najbliższe miasto to Sobótka, gdzie znajduje się końcowa kropka szlaku Sudety Grand Trail',
  },
  {
    id: 47,
    rank: 47,
    rangeName: 'Wyżyna Zabrzeska',
    foreignRangeName: 'Zábřežská vrchovina',
    peakName: 'Lázek',
    peakHeight: 714,
    country: 'CZ',
    isKs: true,
    isKgp: false,
    imageUrl: '/images/mountains/9EMY0F.jpeg',
    description:
      '• Historyczna wieża widokowa z 1933 roku o wysokości 20 metrów\n• Reichlova chata - schronisko górskie na wierzchołku\n• Pomniki upamiętniające członków antyfaszystowskiego ruchu oporu z okresu II wojny światowej\n• Nadajnik telekomunikacyjny na szczycie',
  },
  {
    id: 48,
    rank: 48,
    rangeName: 'Góry Kamienne',
    peakName: 'Boreczna',
    peakHeight: 710,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/6940.jpeg',
    description:
      '• Drugi wierzchołek dwuwierzchołkowego szczytu Mniszek\n• Zbudowany ze skał wylewnych – porfirów i tufów\n• Na stokach głębokie szczeliny związane z dawną działalnością górniczą, najgłębsza o głębokości 36 metrów\n• W wyrobisku dawnego kamieniołomu działa naturalna ściana wspinaczkowa\n• W przeszłości funkcjonowała restauracja z wieżą widokową i muszlą koncertową, wyburzone w 1920 roku',
  },
  {
    id: 49,
    rank: 49,
    rangeName: 'Niski Jesionik',
    foreignRangeName: 'Nízký Jeseník',
    peakName: 'Pomezí',
    peakHeight: 707,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/pm1F8V.jpeg',
    description:
      '• Lokalnie rozpoznawalny punkt grzbietowy w terenie niskich wzgórz, oznaczony jako vrchol na czeskich mapach turystycznych\n• Typowy przykład kopca w krajobrazie Nízký Jeseník charakteryzującym się lasami i pastwinami\n• Miejsce bywa oznaczone tabliczką przy drzewie i traktowane przez piechurów jako punkt szczytowy na trasach pieszych\n• Nie jest to jeden z formalnie katalogowanych wysokich szczytów regionu, ale raczej lokalny punkt orientacyjny w południowo-zachodniej części pasma',
  },
  {
    id: 50,
    rank: 50,
    rangeName: 'Góry Bystrzyckie',
    peakName: 'Kamienna Góra',
    peakHeight: 704,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/ucHMKh.jpeg',
    description:
      '• Ma formę skalistego bastionu o stromych zboczach od wschodu i północy, zbudowanego z piaskowców kredowych\n• Płaska powierzchnia szczytowa pokryta jest rumowiskiem skalnym i dużymi blokami piaskowca kwarcowego\n• Punkt widokowy z panoramą na Polanicę-Zdrój, dawniej popularny cel spacerów kuracjuszy\n• U podnóża XIX-wieczna leśniczówka Kamienna Góra\n• Na zachodniej kulminacji pozostałości Fortu Fryderyka, pruskiej budowli z końca XVIII wieku, związanej z lokalną anegdotą o skoku Augusta Ponzela',
  },
  {
    id: 51,
    rank: 51,
    rangeName: 'Góry Jastrzębie',
    foreignRangeName: 'Jestřebí hory',
    peakName: 'Jański Wierch',
    foreignPeakName: 'Janský vrch',
    peakHeight: 697,
    country: 'PL/CZ',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/8sMBza.jpeg',
    description:
      '• Położony około 2,5 km na południowy zachód od miejscowości Okrzeszyn\n• Zbudowany z górnokarbońskich piaskowców i zlepieńców\n• Masyw częściowo pokryty borem świerkowym charakterystycznym dla tego regionu Sudetów\n• Dostępny szlakiem turystycznym prowadzącym wzdłuż granicy',
  },
  {
    id: 52,
    rank: 52,
    rangeName: 'Grzbiet Jesztedzko-Kozakowski',
    foreignRangeName: 'Ještědsko-kozákovský hřbet',
    peakName: 'Javorník',
    foreignPeakName: 'Javorník',
    peakHeight: 684,
    country: 'CZ',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/960x720_5OfVZo.jpg',
    description:
      '• Potrójny punkt graniczny terenów katastralnych na szczycie\n• W przeszłości stały tu popularne budowle: Obří sud (hotel ponownie otwarty w 2011 roku) oraz wieża Blaschkova\n• Część parku krajobrazowego Ještěd chroniącego wartości przyrodnicze regionu\n• W okolicy ośrodek rekreacyjny z wyciągiem narciarskim i torem saneczkowym',
  },
  {
    id: 53,
    rank: 53,
    rangeName: 'Góry Wałbrzyskie',
    peakName: 'Niedźwiadki',
    peakHeight: 629,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/q0JBO6e.jpeg',
    description:
      '• Trójwierzchołkowe wzniesienie z kulminacjami osiągającymi wysokości 604, 623 i 629 m n.p.m.\n• Szczytowa część zbudowana ze skał wulkanicznych, natomiast zbocza tworzą skały osadowe z pokładami węgla kamiennego\n• Spotykają się tu głazy narzutowe pochodzenia lodowcowego\n• Na północno-zachodnim zboczu pozostałości mauzoleum z czasów III Rzeszy, wzniesionego w latach 1936–1938 według projektu Roberta Tischlera\n• Położone na terenie Wałbrzycha, wyraźnie góruje nad okoliczną zabudową',
  },
  {
    id: 54,
    rank: 54,
    rangeName: 'Masyw Śnieżnika',
    peakName: 'Wapniarka',
    peakHeight: 532,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/d53d.jpeg',
    description:
      '• Drewniana wieża widokowa z 2008 roku jest trzecią w historii tego miejsca - pierwsza z 1889 roku została zniszczona przez piorun w 1925 roku, druga z tego samego roku przetrwała do lat powojennych\n• Charakteryzuje się zróżnicowaną budową geologiczną z występowaniem wapieni krystalicznych\n• U podnóża dawne kamieniołomy wapienia oraz pozostałości pieców wapiennych\n• Wśród roślinności występują fragmenty ciepłolubnej buczyny storczykowej',
  },
  {
    id: 55,
    rank: 55,
    rangeName: 'Góry Stołowe',
    peakName: 'Guzowata',
    peakHeight: 501,
    country: 'PL',
    isKs: false,
    isKgp: false,
    imageUrl: '/images/mountains/NY4DV3.jpeg',
    description:
      '• Nowoczesna platforma widokowa oddana do użytku w 2019 roku, oferująca panoramiczne widoki na Sudety\n• U podnóża Zalew Radkowski pełniący funkcję rekreacyjną\n• Miejsce wydarzeń kulturalnych - w ramach Festiwalu Góry Literatury na tarasie widokowym odbywają się spotkania z pisarzami i twórcami\n• Na platformę prowadzą dwie trasy: łagodniejsza brukowana ścieżka oraz krótsza, ale bardziej stroma droga leśna',
  },
];